
import { Button , LineEdit} from "std-widgets.slint";

export global im {
    // 回车事件
    callback confirm();
}

component Photo {
    in property <image>  img;

    preferred-height: 200px;
    preferred-width: 300px;
    padding: 10px;
    Rectangle {
        border-width: 1px;
        border-color: black;
        border-radius: 1px;
        Image {
            width:  100%;
            height: 100%;
            source: root.img;
            image-fit: contain;
        }
        }
}

export component App inherits Window {
    title: "Image";
    in-out property <string>  name;
    in property <string> value;
    in-out property <image> img1;
    in-out property <image> img2;
    in-out property <image> img3;
    in-out property <image> img4;
    in-out property <string> info;


    preferred-width: 800px;
    preferred-height: 600px;

    VerticalLayout {
        padding: 10px;
        spacing: 10px;
        HorizontalLayout {
            spacing: 20px;
            LineEdit { 
                text: name;
                width: parent.width/2 - 20px;
                // edited(_input) => {
                //     name = _input
                // }
                accepted => {
                        root.img1 = @image-url("");
                        root.img2 = @image-url("");
                        root.img3 = @image-url("");
                        root.img4 = @image-url("");
                        root.name = self.text;
                        self.text = "";
                        im.confirm();
                    }
                }
                
            Text {
                text: "==>>>";
                vertical-alignment: center;
                horizontal-alignment: center;
            }

            Rectangle {
                height: 40px;
                min-width:  260px;
                border-color: black;
                border-width: 1px;
                    Text {text : value;}
            }
        }

        GridLayout {
            spacing: 10px;
            Row {
                Photo{
                    img: root.img1;
                }
                Photo{
                    img: root.img2;
                }
            }
            Row {
                Photo {
                    img: root.img3;
                }
                Photo {
                    img: root.img4;
                }
            }
        }
        Rectangle {
            height: 40px;
            min-width:  260px;
            border-color: black;
            border-width: 1px;
        Text {
            text: info;
            width: parent.width;
            height: parent.height;
            vertical-alignment: center;
            horizontal-alignment: left;
        }
    }
    }
}
